# Generated by Django 5.2.7 on 2025-11-04 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_billdue_calendar_calendarcell'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdue',
            name='recurring',
            field=models.CharField(choices=[('none', 'One-time'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='none', max_length=10),
        ),
    ]
