# Generated by Django 5.2.7 on 2025-11-04 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_billdue_recurring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billdue',
            name='recurring',
        ),
    ]
